version: '3'

services:
  nginx:
    image: docker.yiiman.ir/nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:85:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge